---
- name: Play 1
  hosts: servers
  become: yes
  tasks:
    - name: delete archive
      file:
        path: ~/netology/kafka-3.4.0-src.tgz
        state: absent
    - name: delete catalog kafka
      file: 
        path: ~/netology/kafka/
        state: absent
  tags: play1

- name: Play 2
  hosts: servers
  become: yes
  tasks:
    - name: delete tuned strtup
      service:
        name: tuned
        enabled: false
        state: stopped
    - name: delete tuned
      apt:
        name: tuned
        state: absent
  tags: play2

- name: Play 3
  hosts: servers
  become: yes
  tasks:
    - name: delete new motd
      file:
        path: /etc/motd
        state: absent
    - name: restore motd
      copy:
        src: ~/motd
        dest: /etc/
  tags: play3
...