---
- name: Play 1
  hosts: servers
  become: yes
  tasks:
    - name: delete archive
      file:
        path: ~/netology/kafka-3.4.0-src.tgz
        state: absent
    - name: delete catalog kafka
      file: 
        path: ~/netology/kafka/
        state: absent
  tags: play1

- name: Play2
  hosts: servers
  become: yes
  tasks:
    - name: install tuned
      apt:
        name: tuned
        state: absent
  tags: play2

# - name: Play 3
#   hosts: servers
#   become: yes
#   tasks:
#     - name: change motd
#       debug: msg: "{{ lookup('file', '/etc/motd') }}"
#   tags: play3
...