---
all:  
  hosts:
    elk-01:
      ansible_host: 178.154.202.138
    docker-01:
      ansible_host: 84.252.131.176
  children:
    elk:
      hosts:
        elk-01:
    docker:
      hosts:
        docker-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: aleks