---
- name: install docker
  hosts: all
  become: true
  tasks:
    - name: prepare hosts
      apt:
        name: 
         - gnupg
         - ca-certificates
         - curl
        update_cache: yes
        state: present
    - name: add docker GPG key
      apt_key: url=https://download.docker.com/linux/debian/gpg
    - name: add docker repo 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        filename: /etc/apt/sources.list.d/docker
    - name: install docker and requirements
      apt:
        name:
          - python3-pip 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present

# - name: build and push image
#   hosts: docker
#   become: true
#   vars_files:
#     - vars/variables.yml
#   tasks:
#     - name: copy dockerfile
#       copy:
#         src: ./files
#         dest: .
#     - name: Log into DockerHub
#       docker_login:
#         username: "{{ docker_hub_user }}"
#         password: "{{ docker_hub_password }}"
#     - name: docker build
#       docker_image: 
#         name: aleks9292/netology:0.2
#         build:
#           path: .
#         source: build
#     - name: Tag and push to docker hub
#       docker_image:
#         name: aleks9292/netology:0.2
#         repository: aleks9292/netology:0.2
#         push: yes
#     - name: Log out of DockerHub
#       docker_login:
#         state: absent

- name: install elasticsearch
  hosts: elk
  become: true
  tasks:
    - name: docker pull and run
      docker_image:
        name: aleks9292/netology:0.3
        source: pull
      