version: '3.1'

services:
  db:
    image: postgres:15.1
    container_name: shadrinav-netology-db 
    environment:
      POSTGRES_DB: shadrinav-db
      POSTGRES_PASSWORD: shadrinav12!3!!
    ports:
      - "5432:5432"
    networks:      
      shadrinav-my-netology-hw:        
        ipv4_address: 172.22.0.2    
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: shadrinav-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: shadrinav@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "61231:80"
    networks:
      shadrinav-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4.0
    links:
      - db
    container_name: shadrinav-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shadrinav12!3!!
    ports:
      - "10051:10051"
    networks:
      shadrinav-my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: always    

  zabbix_wgui:
    image: zabbix/zabbix-web-nginx-pgsql
    links:
      - db
      - zabbix-server
    container_name: shadrinav-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: shadrinav12!3!!
      ZBX_SERVER_HOST: "172.22.0.4"
    ports:
      - "80:8080"
    networks:
      shadrinav-my-netology-hw:
        ipv4_address: 172.22.0.5
    restart: always

networks:  
  shadrinav-my-netology-hw:    
    driver: bridge    
    ipam:      
      config:      
      - subnet: 172.22.0.0/24
