version: '3.1'

services:
  db:
    image: postgres:15.1
    container_name: shadrinav-netology-db 
    environment:
      POSTRGRES_DB: shadrinav-db
      POSTGRES_PASSWORD: shadrinav12!3!!
    networks:      
      shadrinav-my-netology-hw:        
        ipv4_address: 172.22.0.2    
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: shadrinav-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: shadrinav@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "61231:80"
    networks:
      shadrinav-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always


networks:  
  shadrinav-my-netology-hw:    
    driver: bridge    
    ipam:      
      config:      
      - subnet: 172.22.0.0/24
