version: "3.7"

services:
  elasticsearch:
    image: aleks9292/netology:latest
    ports:
      - "9200:9200"
      - "9300:9300"


  kibana:
    image: kibana:7.17.12
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch