---
all:  
  hosts:
    postgres-01:
      ansible_host: 84.201.129.186
    postgres-01-test:
      ansible_host: 158.160.104.118
  children:
    postgres:
      hosts:
        postgres-01:
    tests:
      hosts:
        postgres-01-test:
  vars:
    ansible_connection_type: paramiko
    ansible_user: aleks