---
- name: install docker
  hosts: postgres
  become: true
  tasks:
    - name: prepare hosts
      apt:
        name: 
         - gnupg
         - ca-certificates
         - curl
        update_cache: yes
        state: present
    - name:  add docker GPG key
      apt_key: url=https://download.docker.com/linux/debian/gpg
    - name: add docker repo 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        filename: /etc/apt/sources.list.d/docker
    - name: install some required
      apt:
        name:
          - python3-pip 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present
    - name: install module docker
      pip:
        executable: pip3
        name: 
          - docker==6.1.3
          - docker-compose
- name: install postgres
  hosts: postgres
  become: true
  tasks:
    - name: copy docker-compose-manifest
      copy:
        src: ./files
        dest: .
    - name: Tear down existing services
      docker_compose:
        project_src: ./files
        state: absent      
    - name: install postgres
      docker_compose:
        project_src: ./files